export const SET_ROOM = "SET_ROOM"
export const UNSET_ROOM = "UNSET_ROOM"
export const USER_LEFT_ROOM = "USER_LEFT_ROOM"
export const USER_JOINED_ROOM = "USER_JOINED_ROOM"
export const SET_ALL_ROOMS = "SET_ALL_ROOMS"